language: ruby
cache: bundler

rvm:
- 2.1.2

addons:
  postgresql: '9.3'

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database omggenomes_test;' -U postgres
  - bundle exec rake db:create

notifications:
  slack: triplettlab:Labahf3TN0MtJgCffs7xi2za
  email: false

after_success:
  - chmod 600 .travis/deploy_key
  - ssh-add .travis/deploy_key
  - git remote add deploy dokku@austinfanclub.com:genomes
  - git push deploy

env:
  global:
    secure: ZY/412uUphfTSGhCycg4v/9nfzQKS5RO9m6PeKzQiOuZWs9crNbQZv7S6n1zl495xfJk9uBgLseGysE8TUDvEkInUb32YMtP+Jh0U0/r4EkTkS/dMrYnLagkiCehbu+qrwM36uRmgrq7w6J8fL9ofiAO+GS4i/2ydj04hi4zeKw=

# decrypt deploy key
before_install:
  - echo "austinfanclub.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZEz2Ol1pznXytmwMHZnGu3BAX4iIjCdWdILwv7vZnt2EU8mY9pSkgBqs3tJZMl6SD8NXklJlsyftWAVr0Fvx0BLftXWi5+TrXzR6clvxxsWgXUBKkGw+LxVpWnjy0GvCRAbZHnk/clTURAjXhsVWwODmLiHcZ7jbyyZis8iz1NZTICwgf8g0b+itrVFb7l1Rvd+nT0m76MuxXn3vqn7mYOhin803Qg7+CyKcZadFGrTHCho/zHeQZUrhRFxbWtPeQhxKO+95sj9MI+KkuCY7zTNNhsAKl1zsHc+Iij/FbXCRYKRScARiP3EveXwmDdH1G95qzLlDu7+E8WMVGPjgv" >> ~/.known_hosts
  - openssl aes-256-cbc -K $encrypted_dbf285548d10_key -iv $encrypted_dbf285548d10_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
